//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoStarTech
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito
    {
        public int codigoCarrito { get; set; }
        public string codigoProducto { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> cantidadComprar { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<decimal> precioProducto { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
