//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoStarTech
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StarTechEntities : DbContext
    {
        public StarTechEntities()
            : base("name=StarTechEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carrito> carrito { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    
        public virtual int ComprasProc(Nullable<int> identificacionUsuario)
        {
            var identificacionUsuarioParameter = identificacionUsuario.HasValue ?
                new ObjectParameter("identificacionUsuario", identificacionUsuario) :
                new ObjectParameter("identificacionUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ComprasProc", identificacionUsuarioParameter);
        }
    }
}
